apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
        - Chart.yaml
        - values.yaml
    repoURL: https://github.com/StefanKleinhans/application-manifests.git
    targetRevision: HEAD
    path: src/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true