apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: grafana
spec:
  project: monitoring
  source:
    repoURL: https://github.com/StefanKleinhans/application-manifests.git
    targetRevision: HEAD
    path: src/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
